# CCMS Notes

site_name: My Notes on CCMS
site_author: Kyle Weishaar
theme:
  name: 'material'
# Uncomment the line below to specify a new local port if 8000 is busy.
# dev_addr: 127.0.0.1:<your-port-number>`

markdown_extensions:
  - tables
  - admonition #extension for the content boxes https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - pymdownx.details #extension for making content boxes expandable https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - codehilite #code block extension https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
  - pymdownx.superfences # same as above
  - toc:
      permalink: true # this makes the headers into links https://squidfunk.github.io/mkdocs-material/extensions/permalinks/


nav:
- About: index.md
- Topics:
  - The user interface: ui.md
  - Searching for objects: search.md
  - About products and libraries: productlibrary.md
  - Creating topics: topics.md
  - Creating maps: maps.md
  - The document workflow: workflow.md
  - Viewing versions: reviison.md
  - Referencing content: refences.md

